<a href="https://colab.research.google.com/github/aswinsankarpd/ELECTIVE/blob/main/CLASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CLASS 1

In [ ]:
import numpy as np
arr = np.array(43)
arr

array(43)

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [3]:
print(arr.ndim)

3


In [ ]:
arr = np.array([1,2,3,4,5],ndmin=5)
arr

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [23]:
RR = np.eye(5)
RR

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [26]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.random.rand(5)

array([0.67119497, 0.60910403, 0.72474445, 0.30565727, 0.05194437])

In [45]:
np.random.randint(100)

9

In [47]:
import timeit

print(timeit.timeit('output = 10*5'))

0.19203917999993791


##H.W Find the time taken to compute the sum of the first 10 numbers using timeit 


In [51]:
import timeit
code ='''
sum=0
for i in range(1,11):
  sum+=i
'''

print (timeit.timeit(
                    stmt = code,
                     number = 1))


55
0.0018068780000248807


In [54]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
