<a href="https://colab.research.google.com/github/aswinsankarpd/ELECTIVE/blob/main/CLASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CLASS 1

In [ ]:
import numpy as np
arr = np.array(43)
arr

array(43)

In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
print(arr.ndim)

3


In [ ]:
arr = np.array([1,2,3,4,5],ndmin=5)
arr

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [ ]:
RR = np.eye(5)
RR

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.random.rand(5)

array([0.67119497, 0.60910403, 0.72474445, 0.30565727, 0.05194437])

In [ ]:
np.random.randint(100)

9

In [ ]:
import timeit

print(timeit.timeit('output = 10*5'))

0.19203917999993791


##H.W Find the time taken to compute the sum of the first 10 numbers using timeit 


In [ ]:
import timeit
code ='''
sum=0
for i in range(1,11):
  sum+=i
'''

print (timeit.timeit(
                    stmt = code,
                     number = 1))


55
0.0018068780000248807


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr.shape

(2, 5)

#CLASS 2
####Array operations and Indexing

In [6]:
#Addition element wise

x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
print(x+y)
print(np.add(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [12]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = np.arange(start=11, stop=20).reshape(3,3)
print(a)
print(b)
print(np.add(a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [14]:
print(x-y)

print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [15]:
#Element wise multiplication
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [20]:
#Matrix Multiplication
print(np.dot(x,y))
print(x.dot(y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [21]:
print(x)
print(np.sum(x))

[[1. 2.]
 [3. 4.]]
10.0


In [24]:
print(np.sum(x,axis=0)) #Column
print('\n')
print(np.sum(x,axis=1)) #Row

[4. 6.]


[3. 7.]


In [30]:
arr = np.arange(0,11,1)
arr
arr[8]
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[0:5]
arr[0:5] =100
arr
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])
slice_of_arr = arr[0:6]
slice_of_arr
slice_of_arr[:] = 99
slice_of_arr

5


array([99, 99, 99, 99, 99, 99])

In [35]:
arr_copy = arr.copy()
arr_copy
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
